server {
    listen 4201;

    server_name localhost;

    root /usr/share/nginx/html;   # Dossier Angular (après build: dist/...)

    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gérer les erreurs
    error_page 404 /index.html;
}
